export interface Theme {
  label: string;
  value: string;
  primaryButtonColor: string;
  secondaryButtonColor: string;
  bg: string;
  border: string;
  shadow: string;
  textClass: string;
  alignment: string;
  listStyle: string;
  defaultFont: string;
  mainContainerBg: string;
  type: "light" | "dark";
}

export const THEME_CHOICES: Theme[] = [
  // Light Themes
  {
    label: "Sunrise Bliss",
    value: "sunrise",
    primaryButtonColor: "bg-pink-500 hover:bg-pink-600",
    secondaryButtonColor: "bg-orange-200 hover:bg-orange-300 text-pink-700",
    bg: "bg-gradient-to-r from-orange-200 via-pink-300 to-yellow-200",
    border: "border-2 border-pink-300",
    shadow: "shadow-xl",
    textClass: "text-pink-900 font-serif",
    alignment: "text-left",
    listStyle: "list-disc text-pink-700",
    defaultFont: "Montserrat",
    mainContainerBg: "rgba(255,255,255,0.8)",
    type: "light",
  },
  {
    label: "Minty Fresh",
    value: "minty",
    primaryButtonColor: "bg-emerald-500 hover:bg-emerald-600",
    secondaryButtonColor: "bg-green-100 hover:bg-teal-200 text-emerald-700",
    bg: "bg-gradient-to-r from-green-100 via-teal-100 to-lime-100",
    border: "border border-green-300",
    shadow: "shadow-md",
    textClass: "text-emerald-900 font-sans",
    alignment: "text-left",
    listStyle: "list-decimal text-emerald-700",
    defaultFont: "Nunito",
    mainContainerBg: "rgba(255,255,255,0.8)",
    type: "light",
  },
  {
    label: "Golden Hour",
    value: "golden",
    primaryButtonColor: "bg-yellow-500 hover:bg-yellow-600",
    secondaryButtonColor: "bg-orange-200 hover:bg-yellow-200 text-yellow-700",
    bg: "bg-gradient-to-r from-yellow-100 via-orange-100 to-yellow-200",
    border: "border-4 border-yellow-300",
    shadow: "shadow-2xl",
    textClass: "text-yellow-900 font-serif",
    alignment: "text-right",
    listStyle: "list-decimal text-yellow-700",
    defaultFont: "Playfair Display",
    mainContainerBg: "rgba(255,255,255,0.8)",
    type: "light",
  },
  {
    label: "Lavender Dream",
    value: "lavender",
    primaryButtonColor: "bg-purple-500 hover:bg-purple-600",
    secondaryButtonColor: "bg-pink-100 hover:bg-indigo-200 text-purple-700",
    bg: "bg-gradient-to-br from-purple-200 via-indigo-100 to-pink-100",
    border: "border-4 border-purple-200",
    shadow: "shadow-2xl",
    textClass: "text-purple-900 font-mono",
    alignment: "text-right",
    listStyle: "list-none text-purple-700",
    defaultFont: "Lato",
    mainContainerBg: "rgba(255,255,255,0.8)",
    type: "light",
  },
  {
    label: "Oceanic Calm",
    value: "oceanic",
    primaryButtonColor: "bg-cyan-600 hover:bg-cyan-700",
    secondaryButtonColor: "bg-blue-200 hover:bg-cyan-200 text-cyan-800",
    bg: "bg-gradient-to-r from-blue-200 via-cyan-200 to-teal-100",
    border: "border-2 border-blue-300",
    shadow: "shadow-lg",
    textClass: "text-blue-900 font-sans",
    alignment: "text-center",
    listStyle: "list-circle text-cyan-800",
    defaultFont: "Roboto",
    mainContainerBg: "rgba(255,255,255,0.8)",
    type: "light",
  },
  // Dark Themes
  {
    label: "Midnight Indigo",
    value: "midnight",
    primaryButtonColor: "bg-indigo-700 hover:bg-indigo-800",
    secondaryButtonColor: "bg-blue-900 hover:bg-blue-900 text-white",
    bg: "bg-gradient-to-br from-indigo-900 via-gray-900 to-blue-900",
    border: "border-2 border-indigo-700",
    shadow: "shadow-2xl",
    textClass: "text-indigo-100 font-mono",
    alignment: "text-left",
    listStyle: "list-disc text-indigo-300",
    defaultFont: "Roboto Mono",
    mainContainerBg: "rgba(30, 41, 59, 0.95)",
    type: "dark",
  },
  {
    label: "Slate Modern",
    value: "slate",
    primaryButtonColor: "bg-violet-700 hover:bg-violet-800",
    secondaryButtonColor: "bg-purple-900 hover:bg-violet-900 text-violet-300",
    bg: "bg-gradient-to-br from-violet-900 via-violet-800 to-purple-900",
    border: "border-2 border-violet-700",
    shadow: "shadow-xl",
    textClass: "text-violet-100 font-mono",
    alignment: "text-left",
    listStyle: "list-disc text-violet-300",
    defaultFont: "Roboto Mono",
    mainContainerBg: "rgba(49, 24, 77, 0.95)",
    type: "dark",
  },
  {
    label: "Forest Night",
    value: "forest-night",
    primaryButtonColor: "bg-emerald-800 hover:bg-emerald-900",
    secondaryButtonColor: "bg-green-900 hover:bg-emerald-900 text-emerald-300",
    bg: "bg-gradient-to-br from-green-900 via-emerald-800 to-lime-900",
    border: "border border-emerald-700",
    shadow: "shadow-lg",
    textClass: "text-emerald-100 font-sans",
    alignment: "text-center",
    listStyle: "list-dot text-emerald-300",
    defaultFont: "Inter",
    mainContainerBg: "rgba(30, 41, 59, 0.95)",
    type: "dark",
  },
  {
    label: "Rose Quartz Dark",
    value: "rose-dark",
    primaryButtonColor: "bg-fuchsia-700 hover:bg-fuchsia-800",
    secondaryButtonColor: "bg-rose-800 hover:bg-fuchsia-900 text-pink-200",
    bg: "bg-gradient-to-br from-fuchsia-900 via-rose-800 to-pink-700",
    border: "border-2 border-fuchsia-700",
    shadow: "shadow-2xl",
    textClass: "text-fuchsia-100 font-sans",
    alignment: "text-center",
    listStyle: "list-disc text-pink-200",
    defaultFont: "Rubik",
    mainContainerBg: "rgba(55, 7, 55, 0.92)",
    type: "dark",
  },
  {
    label: "Charcoal Classic",
    value: "charcoal",
    primaryButtonColor: "bg-rose-700 hover:bg-amber-900",
    secondaryButtonColor: "bg-amber-900 hover:bg-rose-900 text-amber-300",
    bg: "bg-gradient-to-r from-rose-900 via-amber-900 to-rose-700",
    border: "border-2 border-rose-700",
    shadow: "shadow-2xl",
    textClass: "text-rose-100 font-sans",
    alignment: "text-right",
    listStyle: "list-decimal text-amber-300",
    defaultFont: "Open Sans",
    mainContainerBg: "rgba(67, 20, 36, 0.95)",
    type: "dark",
  },
];
